# 正交化

In [147]:
import numpy as np
import random
from numpy.linalg import matrix_rank

#控制小数点精度
np.set_printoptions( precision=3, suppress=True )

#classic施密特正交化实现的QR分解
#可以应用于非方阵！！！
#其中Q是正交矩阵（行大于等于列），R是上三角矩阵
def QR_Factor(A,isprint=False):
    #矩阵运算都用numpy来处理
    A=np.array(A).astype(np.float32)
    (m,n)=A.shape

    #首先保证矩阵的秩等于列数（因为行大于等于列）
    rk=matrix_rank(A)
    if rk!=n:
        print('必须列满秩 A!!!')
        return -1

    #初始化Q，R矩阵
    Q=A.copy()
    R=np.zeros(A.shape)
    ok_column=0#表示已经正交化过的列数
    #对于A每一列做正交化
    for x in A.T:#对于每一列
        u=np.copy(x)
        for columnj in range(ok_column):
            # 计算投影长度并填入R矩阵中
            projection_length = Q[:, columnj].T @ x / (Q[:, columnj].T @ Q[:, columnj])
            R[columnj, ok_column] = projection_length
            # 减去投影分量以实现正交
            u -= projection_length * Q[:, columnj]
            if isprint:
                print(f"第{columnj}列，正交u:", u)
                print("R:", R)
        norm = np.linalg.norm(u)  # 模长
        R[ok_column, ok_column] = norm  # 模长填入对角线

        Q[:, ok_column] = u / norm  # 归一化得到标准正交向量
        if isprint:

            print("R:",R)
            print("归一化Q:",Q)
        ok_column+=1
    #去掉R多余的行，保证是方阵
    if m!=n:
        R=np.delete(R,[n,m-1],axis=0)

    return Q,R


In [2]:
import numpy as np

def schmidt_orthogonalization(vectors):
    orthogonal_vectors = []
    for v in vectors:
        temp = v.astype(np.float64)  # 将向量转换为float64类型
        for ov in orthogonal_vectors:
            temp -= np.dot(v.astype(np.float64), ov) / np.dot(ov, ov) * ov
        orthogonal_vectors.append(temp / np.linalg.norm(temp))
    return np.array(orthogonal_vectors)

# 示例使用
A=np.array([
[1,19,-34],
[-2,-5,20],
[2,8,37]])
orthogonal_A = schmidt_orthogonalization(A.T)
print(orthogonal_A)

[[ 0.33333333 -0.66666667  0.66666667]
 [ 0.93333333  0.33333333 -0.13333333]
 [-0.13333333  0.66666667  0.73333333]]


In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [ ]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [148]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

# G

In [149]:
import numpy as np

#控制小数点精度
np.set_printoptions( precision=3, suppress=True )

#旋转矩阵实现的正交规约 PA=T
#可以应用于非方阵！！！
#其中P是正交矩阵(方阵)，T是伪上三角矩阵（可以不是方阵）
def create_Tpq_A(n, p, q, c, s):
    T_pq = np.eye(n)#, dtype=complex
    # 更新矩阵的指定位置
    T_pq[p, p] = np.conj(c)  # 对角线位置 (p, p) 为 c 的共轭
    T_pq[q, q] = c           # 对角线位置 (q, q) 为 c
    T_pq[p, q] = np.conj(s)  # 位置 (p, q) 为 s 的共轭
    T_pq[q, p] = -s          # 位置 (q, p) 为 -s
    return T_pq
def Givens_Reduction(A):
    #矩阵运算都用numpy来处理
    A=np.array(A)
    (m,n)=A.shape
    #首先初始化P，T矩阵
    Q=np.identity(m)
    R=np.copy(A)
    #按顺序每一列进行变换
    for columnj in range(n):
        for rowi in range(m-1,columnj,-1):
            #首先得到要变换的两个数
            x=R[columnj,columnj]
            y=R[rowi,columnj]
            norm=np.sqrt(x**2+y**2)
            #直接构造旋转矩阵
            c=x/norm
            s=y/norm
            P_ij=create_Tpq_A(m,columnj,rowi,c,s)
            #累乘可以得到最终的P和T矩阵
            Q=P_ij@Q
            R=P_ij@R
            print(f"第i步骤P({rowi},{columnj})={P_ij}\n R是={R}\n ")

    #由于要求是求矩阵分解，所以转化为QR分解的形式
    Q_A=Q.T#由于P是正交方阵，所以转置=逆

    return Q_A,R

# H 

In [150]:
import numpy as np
import math

#控制小数点精度
np.set_printoptions( precision=3, suppress=True )
def vector_norm(vector):
    # 使用numpy的dot计算向量内积，再开平方根得到模长
    return math.sqrt(np.dot(vector, vector))
def normalize_vector(vector):
    # 计算向量的模长
    norm = vector_norm(vector)
    if norm == 0:# 如果模长为0，返回原0向量
        return vector
    return vector / norm
#对称矩阵实现的正交规约 PA=T
#可以应用于非方阵！！！
#其中P是正交矩阵(方阵)，T是伪上三角矩阵（可以不是方阵）
def Householder_Reduction(A,isprint=False):
    #矩阵运算都用numpy来处理
    A=np.array(A).astype(np.float32)
    (len_r,len_c)=A.shape

    Q=np.identity(len_r)
    #分别处理两种不是方阵的情况
    if len_r > len_c:
        iter_num=len_c
    else:
        iter_num=len_r-1

    for idx in range(iter_num):
        #首先构造ei向量
        e = np.zeros(len_r-idx)
        e[0] = 1
        I = np.identity(len_r-idx)
        #注意u要是列向量
        a = A[idx:,idx]#每行向量
        u = A[idx:,idx].T - vector_norm(a)*e.T
        u = normalize_vector(u)
        exp_u = np.expand_dims(u,axis=0)
        #得到反射算子
        Rflt = I - 2.0*exp_u.T@exp_u
        #拓展成正常大小
        Hi = np.identity(len_r)
        Hi[idx:,idx:] = Rflt
        #更新
        Q = Hi@Q
        A = Hi@A
        if isprint:
            print(f"第{idx}步，u是{u},Rflt是{Rflt}\n,Q{Q}\nHiiiA是{A}\n")

    Q_A=Q.T
    R_A=A
    return Q_A,R_A


# 结果

In [151]:
import numpy as np

A=np.array(    [
[1,19,-34],
[-2,-5,20],
[2,8,37]])


# Q, R = np.linalg.qr(A)

# print("矩阵 Q：\n", Q)
# print("矩阵 R：\n", R)
Q,R=Householder_Reduction(A)
# 矩阵 Q：
#  [[-0.333 -0.933 -0.133]
#  [ 0.667 -0.333  0.667]
#  [-0.667  0.133  0.733]]
# 矩阵 R：
#  [[ -3. -15.   0.]
#  [  0. -15.  30.]
#  [  0.   0.  45.]]
Q@R


array([[  1.,  19., -34.],
       [ -2.,  -5.,  20.],
       [  2.,   8.,  37.]])

In [152]:
Givens_Reduction(A)

第i步骤P(2,0)=[[ 0.447  0.     0.894]
 [ 0.     1.     0.   ]
 [-0.894  0.     0.447]]
 R是=[[  2.236  15.652  17.889]
 [ -2.     -5.     20.   ]
 [  0.    -13.416  46.957]]
 
第i步骤P(1,0)=[[ 0.745 -0.667  0.   ]
 [ 0.667  0.745  0.   ]
 [ 0.     0.     1.   ]]
 R是=[[  3.     15.     -0.   ]
 [  0.      6.708  26.833]
 [  0.    -13.416  46.957]]
 
第i步骤P(2,1)=[[ 1.     0.     0.   ]
 [ 0.     0.447 -0.894]
 [ 0.     0.894  0.447]]
 R是=[[  3.  15.  -0.]
 [  0.  15. -30.]
 [  0.   0.  45.]]
 


(array([[ 0.333,  0.933, -0.133],
        [-0.667,  0.333,  0.667],
        [ 0.667, -0.133,  0.733]]),
 array([[  3.,  15.,  -0.],
        [  0.,  15., -30.],
        [  0.,   0.,  45.]]))

In [153]:

QR_Factor(A)

(array([[ 0.333,  0.933, -0.133],
        [-0.667,  0.333,  0.667],
        [ 0.667, -0.133,  0.733]], dtype=float32),
 array([[  3.,  15.,   0.],
        [  0.,  15., -30.],
        [  0.,   0.,  45.]]))

# solve Ax=b

In [154]:
def solve_qr(Q,R, b):
    # A=QR  x=A-1b   x=R-1Q-1b
    Q_T_b = Q.T@ b
    x =  np.linalg.inv(R)@Q_T_b
    return x

#判断方程Ax=b是否有解
def is_solvable(A,b):
    Ab=np.concatenate((A,np.expand_dims(b,axis=0).T),axis=1)
    #如果增广矩阵的秩等于A的秩就有解
    return matrix_rank(A)==matrix_rank(Ab)

#输入的Q可能不是方阵
#结果可能是最小二乘解！！！！！
def solveQR(Q,R,b):
    dim=R.shape[1]
    #等价于求解 Rx=Q.Tb
    QTb=np.dot(Q.T,b)
    #去掉R和b多余的行
    if R.shape[0]!=R.shape[1]:
        R=np.delete(R,[R.shape[1],R.shape[0]-1],axis=0)
        QTb=QTb[:R.shape[1]]
    #回代法求解Rx=Q.Tb,上三角形式
    #但是这个方程不一定有解，要分情况讨论
    if is_solvable(R,QTb):#1.方程有解
        x=np.copy(QTb)
        for idx in range(dim-1,-1,-1):#从后往前
            x[idx]=QTb[idx]#得到等式和
            for i in range(idx+1,dim):
                x[idx] -= R[idx][i]*x[i]#减去前面的分量
            if int(R[idx][idx])==0:#2.如果R对角线存在0，那就是有无穷解
                #由于是无穷解，所以随便给出一个解即可
                x[idx] = random.randrange(-100,100)/10.0
            else:#3.唯一解
                x[idx] = float(x[idx])/R[idx][idx]#注意U的对角不是1
            print('x[{}] = {}'.format(idx,x[idx]))
    else:#方程无解
        return -1
    return x

A1 = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2, 3])
Q,R=QR_Factor(A1)
x = solve_qr(Q,R, b)
x = solveQR(Q,R, b)
print(x)



x[1] = 8.3
x[0] = -9.805713928655456
[-9.806  8.3  ]
